[package]
name = "ndproxy"
version = "0.1.0"
authors = ["Zhang Zongyu <zongyu@novazy.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
getset = "0.1.1"
ipnet = "2.3.1"
pnet = "0.28.0"
config = "0.11"
futures = "0.3.11"
tokio = { version = "1.8.1", features = ["full"] }
socket2 = { version="0.4.0", features=["all"] }
rtnetlink = "0.8.0"
netlink-packet-route = "0.7.1"