[package]
name = "ndproxy"
version = "0.3.1"
authors = ["Zhang Zongyu <zongyu@novazy.net>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/6-6-6/ndproxy"
homepage = "https://github.com/6-6-6/ndproxy"
description = "Proxying Neighbor Discovery packets among interfaces."
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
address_translation = "0.1.2"
classic_bpf = "0.1.1"
config = { version = "0.13.3", features = ["toml"] }
futures = "0.3.28"
getset = "0.1.2"
ipnet = "2.7.2"
libc = "0.2.146"
log = { version = "0.4.19", features = ["release_max_level_info"] }
pnet = "0.33.0"
pretty_env_logger = "0.5.0"
socket2 = { version = "0.5.3", features = ["all"] }
tokio = { version = "1.28.2", features = ["sync", "rt-multi-thread", "macros"] }
ip_network_table-deps-treebitmap = "0.5.0"
ttl_cache = "0.5.1"
thiserror = "1.0.40"
clap = { version = "4.3.4", features = ["derive"] }

[features]
dev = []

[profile.release]
codegen-units = 1
lto = "fat"
