[package]
name = "ndproxy"
version = "0.1.0"
authors = ["Zhang Zongyu <zongyu@novazy.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
argparse = "0.2.2"
config = "0.11"
futures = "0.3.11"
getset = "0.1.1"
ipnet = "2.3.1"
log = { version = "0.4.14", features = ["release_max_level_info"] }
netlink-packet-route = "0.7.1"
pnet = "0.28.0"
pretty_env_logger = "0.4.0"
rand = "0.8.4"
rtnetlink = "0.8.0"
socket2 = { version = "0.4.0", features = ["all"] }
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros"] }

[profile.release]
codegen-units = 1
lto = "fat"