[package]
name = "ndproxy"
version = "0.1.3"
authors = ["Zhang Zongyu <zongyu@novazy.net>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/6-6-6/ndproxy"
homepage = "https://github.com/6-6-6/ndproxy"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
address_translation = { git = "https://github.com/6-6-6/utils" }
argparse = "0.2.2"
classic_bpf = { git = "https://github.com/6-6-6/classic_bpf" }
config = { version = "0.11", features = ["toml"] }
futures = "0.3.11"
getset = "0.1.1"
ipnet = "2.3.1"
log = { version = "0.4.14", features = ["release_max_level_info"] }
netlink-packet-route = "0.7.1"
pnet = "0.28.0"
pretty_env_logger = "0.4.0"
rand = "0.8.4"
rtnetlink = "0.8.0"
socket2 = { version = "0.4.0", features = ["all"] }
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros"] }
libc = "0.2.98"

[profile.release]
codegen-units = 1
lto = "fat"

