[package]
name = "ndproxy"
version = "0.2.3"
authors = ["Zhang Zongyu <zongyu@novazy.net>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/6-6-6/ndproxy"
homepage = "https://github.com/6-6-6/ndproxy"
description = "Proxying Neighbor Discovery packets among interfaces."
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
address_translation = "0.1.1"
argparse = "0.2.2"
classic_bpf = "0.1.1"
config = { version = "0.13", features = ["toml"] }
futures = "0.3.16"
getset = "0.1.1"
ipnet = "2.3.1"
libc = "0.2.98"
log = { version = "0.4.14", features = ["release_max_level_info"] }
pnet = "0.28.0"
pretty_env_logger = "0.4.0"
socket2 = { version = "0.4.1", features = ["all"] }
tokio = { version = "1.9.0", features = ["sync", "rt-multi-thread", "macros"] }
ip_network_table-deps-treebitmap = "0.5.0"
ttl_cache = "0.5.1"
thiserror = "1.0.40"
clap = { version = "4.3.4", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = "fat"
